language: java
sudo: false
cache:
    directories:
        - $HOME/.m2/repository
jdk:
    - oraclejdk8
after_success:
    - mvn clean test cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
